# Generated by Django 4.2.11 on 2026-04-30 05:28

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginotpchallenge_user_two_factor_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginotpchallenge',
            new_name='accounts_lo_challen_1f40ff_idx',
            old_name='accounts_lo_challen_2f3099_idx',
        ),
        migrations.AlterField(
            model_name='loginotpchallenge',
            name='challenge_id',
            field=models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True),
        ),
    ]
