# Generated by Django 4.2.11 on 2026-06-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_lo_challen_2f3099_idx_accounts_lo_challen_1f40ff_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('leadership', 'Leadership'), ('manager', 'Project Manager'), ('resource', 'Resource'), ('client', 'Client')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('leadership', 'Leadership'), ('manager', 'Project Manager'), ('resource', 'Resource'), ('client', 'Client')], db_index=True, default='resource', max_length=20),
        ),
    ]
