# Generated by Django 4.2.11 on 2026-06-02 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_resourcenotificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcenotificationpreference',
            name='updated_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'leadership', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
