# Generated by Django 4.2.11 on 2026-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_timeentry_clock_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetreminderlog',
            name='slot_label',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
